language: node_js
sudo: false

deploy:
  provider: pages
  on:
    tags: true
  repo: thingsym/password-generator
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
