language: node_js

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  on:
    tags: true
  repo: thingsym/password-generator
  target_branch: gh-pages
  local-dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
